# Generated by Django 4.0.1 on 2022-01-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_super_user', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(null=True)),
                ('last_login', models.DateField(auto_now=True, verbose_name='Last login')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Date joined')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
