# Generated by Django 4.0.1 on 2022-02-01 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('received_amount', models.FloatField()),
                ('transaction_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_from', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
