# Generated by Django 4.0.1 on 2022-02-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletType',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type_id',
            field=models.CharField(choices=[('saving', 'saving'), ('household', 'household'), ('school', 'school')], max_length=30),
        ),
    ]
