# Generated by Django 4.0.1 on 2022-01-28 13:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user_id', 'wallet_type_id')},
        ),
    ]
