# Generated by Django 4.0.1 on 2022-01-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='to',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user_id',
        ),
    ]
