# Generated by Django 4.0.1 on 2022-02-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
